services:
  edulution-manager-agent:
    image: ghcr.io/edulution-io/edulution-manager/edulution-manager-agent
    restart: always
    container_name: edulution-manager-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/edulution-ui:/srv/docker/edulution-ui
    environment:
      - NODE_ENV=production
      - EDU_MANAGER_INSTALL_TOKEN=<EDU_MANAGER_INSTALL_TOKEN>
    networks:
      - edulution-ui_default

networks:
  edulution-ui_default:
    external: true
