services:
  edulution-wireguard:
    image: ghcr.io/edulution-io/edulution-wireguard:latest
    container_name: edulution-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    volumes:
      - /srv/docker/edulution-ui/data:/etc/wireguard
      - /lib/modules:/lib/modules
    environment:
      - IPNETWORK=<EDU_WG_NETWORK>
      - ADDRESS=<EDU_WG_ADDRESS>
      - EDU_WG_API_KEY=${EDU_WG_API_KEY}
      - DNS=<EDU_WG_DNS>
      # - LOG_LEVEL=${LOG_LEVEL:-INFO} #DEBUG, INFO, WARNING, ERROR
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - edulution-ui_default

networks:
  edulution-ui_default:
    external: true
